from langchain_google_genai import ChatGoogleGenerativeAI
# Import message types to structure the conversation properly for the LLM:
# - SystemMessage: Sets the overall behavior/persona of the AI (the system prompt).
# - HumanMessage: Represents the input/questions typed by the user.
# - AIMessage: Represents the responses generated by the AI model.
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from dotenv import load_dotenv

load_dotenv()

model = ChatGoogleGenerativeAI(model='gemini-flash-lite-latest')

# We initialize a list to keep track of the conversation history. 
# This is required because LLMs are "stateless" by default (they don't remember past messages).
# By storing the history, we can pass it all back to the AI each turn so it understands the context.
# We start the history with a SystemMessage to give the AI its initial instructions.
chat_history = [
    SystemMessage(content='You are a helpful AI assistant')
]

# Create an infinite loop to keep the conversation going until the user types 'exit'
while True:
    user_input = input('You: ')
    
    # Wrap the user's raw text in a HumanMessage object and add it to our history list
    chat_history.append(HumanMessage(content=user_input))
    
    if user_input == 'exit':
        break
        
    # We pass the ENTIRE chat_history list to the model. 
    # Because the list contains all previous back-and-forth messages, 
    # the model can read them all and answer contextually (e.g., remembering a number from 2 messages ago).
    result = model.invoke(chat_history)
    
    # Wrap the model's new response in an AIMessage object and append it to the history
    # so it remembers its own past answers in future turns.
    chat_history.append(AIMessage(content=result.content[0]['text']))
    
    print("AI: ",result.content[0]['text'])

print(chat_history)